# This is a basic workflow to help you get started with Actions

name: CI

#写法一：在push事件时触发构建
on: [push] 

jobs:
  build-qq-ci: 

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@master
    - name: Build 
      uses: docker://qqminiapp/build:latest 
      env: 
        PLUGIN_VERSION: 1.0.0
        PLUGIN_DESC: CI自动构建上传
        PLUGIN_APPTOKEN: fe94b1b3211cb0772125e160276e1d87
        PLUGIN_BUILDUSER: 13246190524@163.com
        PLUGIN_EXPERIENCE: true 
        #PLUGIN_FIRSTPAGE: pages/index/index
        #PLUGIN_USEPACKAGEJSON: true
        #PLUGIN_NPMBUILD: true
        #PLUGIN_SOURCECODEPATH: ./test
